name: CI
on: push
jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Check style
        uses: DoozyX/clang-format-lint-action@v0.12
        with:
          clangFormatVersion: 12
          exclude: ./third_party
          extensions: 'cc,h,h.in'
  test:
    needs: style
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Build
        run: |
          mkdir -p build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          cmake --build . --parallel --config Release
          ctest --verbose --build-config Release
